[tox]
envlist = py, lint

[testenv:lint]
skip_install = true
deps =
    black
    isort
    flake8
    mypy
    numpy
commands =
    isort naturalneighbor tests demo setup.py
    black naturalneighbor tests demo setup.py
    flake8 .
    mypy naturalneighbor

[testenv]
allowlist_externals = bash
basepython =
    py310: python3.10
deps =
    readme_renderer
    flake8
    cpplint
    pytest
    numpy
commands =
    python setup.py check -m -r -s
    pip install -r tests/requirements.txt
    flake8 .
    #cpplint --linelength=100 --recursive naturalneighbor
    pip install -e .
    pytest
    pip install -r demo/demo-requirements.txt
    python demo/demo.py
    bash ./cpptests/test.sh

[flake8]
exclude = .tox,*.egg,build,data
select = E,W,F
max-line-length = 120
ignore = E402,E203
